
jdk:
  - oraclejdk8

env:
  - EPICS_PVAS_INTF_ADDR_LIST=127.0.0.1 EPICS_PVA_ADDR_LIST=127.0.0.1 EPICS_PVA_AUTO_ADDR_LIST=false
  
before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.3.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.3.deb

install:
  - sudo apt-get update
  - sudo apt-get install python-nose
  
before_script:
  - sleep 10
  - 'echo "script.inline: on" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - 'echo "script.inline: on" | sudo tee -a /etc/elasticsearch/indexed.yml'
  - sudo /etc/init.d/elasticsearch start
  - sleep 25
  - curl -XGET 'http://localhost:9200/_cluster/health?pretty'
  - pwd
  - find . -name mapping_definitions.sh
  - chmod a+x src/main/resources/mapping_definitions.sh
  
script:
  - src/main/resources/mapping_definitions.sh
  - mvn clean verify -f pom.xml

after_script:
  - sudo /etc/init.d/elasticsearch stop
